image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init Repo Tooling
    init: npm i

vscode:
  extensions:
    - "standard.vscode-standard"
    - "rust-lang.rust-analyzer"
    - "graphql.vscode-graphql"
    - "svelte.svelte-vscode"
    - "koihik.vscode-lua-format"
